# Generated by Django 4.1.3 on 2022-11-30 18:43

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        CreateExtension("postgis"),
    ]
