# Generated by Django 4.1.3 on 2022-12-03 19:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("polygon", "0001_enable_postgis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=15, null=True)),
                ("language", models.CharField(max_length=2, null=True)),
                ("currency", models.CharField(max_length=3, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=256)),
                ("price", models.DecimalField(decimal_places=3, max_digits=10)),
                ("geo_info", django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
