# Generated by Django 4.1.3 on 2022-12-04 19:01

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polygon", "0004_servicearea_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicearea",
            name="price",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal("0.000"))]
            ),
        ),
    ]
