version: "3.9"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - .nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/usr/src/app/static/
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    image: "${APP_IMAGE}"
    command: ["gunicorn", "app.wsgi", "--bind", "0.0.0.0:8000"]
    volumes:
      - static:/usr/src/app/static/
    env_file:
      - .env

volumes:
  static:
