name: Lint & Test

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/python.lint-and-test.yml"
      - "app/**"
  pull_request:
    paths:
      - ".github/workflows/python.lint-and-test.yml"
      - "app/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: pip install -U pip setuptools wheel
      - run: pip install -r requirements.txt

      - run: black --diff --check $(git ls-files '*.py')
      - run: pylint $(git ls-files '*.py')

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_PASSWORD: test_pass
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - run: sudo apt-get update && sudo apt-get install -y binutils libproj-dev gdal-bin
      - run: pip install -U pip setuptools wheel
      - run: pip install -r requirements.txt

      - run: python manage.py test
        working-directory: app
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: test_db
          DB_USER: test_user
          DB_PASSWORD: test_pass
